CREATE OR REPLACE VIEW valid_customer_orders AS
SELECT
    customer_id,
    customer_segment,
    customer_city,
    customer_state,
    customer_country,
    order_id,
    order_date_dateorders,
    order_status,
    order_region,
    order_city,
    order_state,
    order_country,
    market,
    order_item_id,
    product_card_id,
    order_item_quantity,
    sales,
    order_item_total,
    order_item_discount,
    order_profit_per_order,
    product_name,
    product_price,
    product_category_id,
    department_name,
    category_name,
    shipping_date_dateorders,
    shipping_mode,
    delivery_status,
    late_delivery_risk,
    actual_shipping_days,
    scheduled_shipping_days,
    valid_purchase,
    delay_days
FROM customer_order_base
WHERE valid_purchase = 1;